[
    { "alternateImageData" : [ { "imageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_60X60.gif",
    "lgImageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_500X500.jpg",
    "name" : null
},
    { "imageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV_60X60.gif",
        "lgImageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV_500X500.jpg",
        "name" : null
    },
    { "imageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV1_60X60.gif",
        "lgImageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV1_500X500.jpg",
        "name" : null
    },
    { "imageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV2_60X60.gif",
        "lgImageSrc" : "http://i-e3.walmartimages.com/i/p/00/79/23/43/23/0079234323252_AV2_500X500.jpg",
        "name" : null
    }
],
    "comparable" : true,
    "customerRatingUrl" : "http://aguevara-linux.corp.walmart.com/i/CustRating/4_1.gif",
    "electronicDelivery" : false,
    "genericContent" : { "accessoriesIncluded" : null,
        "accessoriesNotIncluded" : null,
        "addlWarnMsgA" : null,
        "addlWarnMsgB" : null,
        "ageRange" : null,
        "altWarnMsg" : "N",
        "alternateViews" : "3",
        "assembledCountryOfOrigin" : "Imported",
        "attribute1_order" : 3,
        "attribute2_order" : 3,
        "attribute3_order" : 3,
        "attributeData" : [  ],
        "attributeName1" : null,
        "attributeName2" : null,
        "attributeName3" : null,
        "attributeRanking1" : 1,
        "attributeRanking2" : 1,
        "attributeRanking3" : 1,
        "attributeType1" : null,
        "attributeType2" : null,
        "attributeType3" : null,
        "attributeUISetting1" : null,
        "attributeUISetting2" : null,
        "attributeUISetting3" : null,
        "attributeValue1" : null,
        "attributeValue2" : null,
        "attributeValue3" : null,
        "brandName" : "Sceptre",
        "componentsCountryOfOrigin" : "Imported",
        "dimensionX" : 22.129999999999999,
        "dimensionY" : 31.260000000000002,
        "dimensionZ" : 7.8799999999999999,
        "gender" : null,
        "hasMatureContent" : false,
        "imageId" : -9223372036854775808,
        "itemId" : 15739136,
        "itemName" : "Sceptre 32\" Class LCD 720p 60Hz HDTV, X322BV-HD",
        "itemShortName" : null,
        "logoImage" : "http://i-e3.walmartimages.com/i/icon/-9/22/33/72/03/-9223372036854775808_100X60.gif",
        "longDescription" : "<strong>Sceptre 32\" X322BV-HD LCD HDTV:</strong><li>16:9 LCD panel</li><li>With 1366 x 768 resolution</li><li>Wide 178-degree vertical and 178-degree horizontal angles</li><li>See a clear picture from anywhere in the room on the Sceptre 32\" LCD HDTV </li><li>Built-in ATSC digital/NTSC analog/Clear QAM tuner</li><li>Watch digital broadcasts, including HDTV programs where available</li><li>High brightness of 420 cd/m2 with 6.5 ms response time</li><li>Place your Sceptre 32\" LCD HDTV anywhere</li><li>3000:1 dynamic contrast ratio</li><li>HDMI Inputs: 3</li><li>Enjoy a superior HD experience on this 720p 60Hz model with the HDMI one-cable solution</li><li>31.5\" screen of this 720p model is measured diagonally from corner to corner </li>",
        "manufacturerName" : null,
        "mfgNo" : "X322BV-HD",
        "modelNum" : "X322BV-HD",
        "originalBaseUPC" : "0079234323252",
        "panZoomId" : 2,
        "partnerId" : -1,
        "platform" : null,
        "rank" : 1,
        "rating" : null,
        "shelfDescription" : "<li>31.5\" screen measured diagonally from corner to corner <LI>HDMI inputs: 3<li>Wall-mountable, detachable base<li>High brightness of 420 cd/m2 with 6.5 ms response time",
        "shortDescription" : "<p>The sleek Sceptre X322BV-HD HDTV delivers crystal-clear pictures and brings out the best in HD programming. Featuring a 3,000:1 dynamic contrast ratio, this LCD HDTV produces vivid pictures in a widescreen aspect ratio, so you can enjoy the picture from anywhere in your room. It can also be used as a computer monitor via the VGA port. It features three HDMI ports and boasts a competent 6.5ms response time, which makes it popular with avid console gamers. The digital broadcast HDTV can render a maximum resolution of 1366 x 768 pixels. The Sceptre 32\" class LCD 720p 60 Hz HDTV comes with a built-in ATSC digital/ NTSC analog/Clear QAM tuner that allows for a wide array of possible input formats. Unlike older audio-video formats, the single cable HDMI port transmits high definition video and audio together without using multiple cables. The TV features a neat, intuitive interface that helps you operate it easily without the bundled remote.</p>",
        "sourceId" : 2,
        "supplierWarranty" : null,
        "variantAttrData" : null,
        "warrantyLength" : "1 Year"
    },
    "hazardMaterial" : false,
    "id" : 15739136,
    "imagePostCardURL" : "http://i.walmartimages.com/i/p/00/79/23/43/23/0079234323252_150X150.jpg",
    "imageThumbnailURL" : "http://i.walmartimages.com/i/p/00/79/23/43/23/0079234323252_60X60.gif",
    "itemAttributes" : [ { "attrDisplayName" : "Brightness",
        "attributeDisplayOrder" : 4,
        "attributeName" : "Brightness",
        "attributeValue" : "420cd/m2",
        "contentProviderId" : 2,
        "glossaryId" : 0,
        "groupDisplayOrder" : 23,
        "groupName" : "Additional Specifications",
        "itemID" : 15739136
    },
        { "attrDisplayName" : "Response Time",
            "attributeDisplayOrder" : 6,
            "attributeName" : "Response Time",
            "attributeValue" : "6.5ms",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Remote Included",
            "attributeDisplayOrder" : 21,
            "attributeName" : "Remote Included",
            "attributeValue" : "Yes",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Resolution",
            "attributeDisplayOrder" : 22,
            "attributeName" : "Resolution",
            "attributeValue" : "720p (HDTV)",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Ships In Original Packaging",
            "attributeDisplayOrder" : 23,
            "attributeName" : "Ships In Original Packaging",
            "attributeValue" : "Yes",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Tv Definition",
            "attributeDisplayOrder" : 24,
            "attributeName" : "Tv Definition",
            "attributeValue" : "HDTV",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Tv Technology",
            "attributeDisplayOrder" : 25,
            "attributeName" : "Tv Technology",
            "attributeValue" : "LCD",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Primary Color",
            "attributeDisplayOrder" : 108,
            "attributeName" : "Primary Color",
            "attributeValue" : "Black",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Multi Pack Indicator",
            "attributeDisplayOrder" : 145,
            "attributeName" : "Multi Pack Indicator",
            "attributeValue" : "No",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        },
        { "attrDisplayName" : "Battery Type",
            "attributeDisplayOrder" : 146,
            "attributeName" : "Battery Type",
            "attributeValue" : "Does Not Contain a Battery",
            "contentProviderId" : 2,
            "glossaryId" : 0,
            "groupDisplayOrder" : 23,
            "groupName" : "Additional Specifications",
            "itemID" : 15739136
        }
    ],
    "itemFlags" : "1,",
    "media" : false,
    "originalBaseUpc" : "0079234323252",
    "partnerId" : -1,
    "ppueligible" : false,
    "productImageUrl" : "http://i.walmartimages.com/i/p/00/79/23/43/23/0079234323252_215X215.jpg",
    "putEligible" : false,
    "rebate" : false,
    "sellers" : { "0" : { "97CentShipping" : false,
        "availableShippingOfferCodes" : null,
        "baseItemPrice" : 197.0,
        "baseSuggPrice" : 249.99000000000001,
        "checksum" : -1,
        "combinedThresholdEligible" : false,
        "contributesToThreshold" : false,
        "currentItemPrice" : 189.0,
        "displayStatus" : 3,
        "employeeDiscountable" : true,
        "fedExEligible" : false,
        "freeReturns" : false,
        "freeShipping" : false,
        "fromPPU" : -9.223372036854776E+18,
        "giftWrapTaxCode" : "2038857",
        "hasRebateLink" : false,
        "is97CentShipping" : false,
        "isFreeShipping" : false,
        "isPIPEligible" : "Y",
        "isS2SOnly" : false,
        "itemEligibleForFedEx" : false,
        "itemId" : 15739136,
        "maxPrice" : 189.0,
        "maxPromotionAmount" : -9.223372036854776E+18,
        "maximumItems" : 1,
        "minPrice" : 189.0,
        "minPromotionAmount" : -9.223372036854776E+18,
        "packingSlipCode" : 0,
        "ppu" : -9.223372036854776E+18,
        "priceChangeCode" : 5,
        "productTaxCode" : "PTG8",
        "promotionDiscount" : -9.223372036854776E+18,
        "promotionMessageType" : "",
        "rebateAmount" : -9.223372036854776E+18,
        "rebateTargetURL" : null,
        "remapAction" : null,
        "remapToItemId" : -9223372036854775808,
        "s2SE" : true,
        "sellerId" : 0,
        "sellerItemFlags" : "8,",
        "sellerName" : "Walmart.com",
        "sellerTypeId" : 1,
        "shipAlone" : true,
        "shippingDimX" : 25.600000000000001,
        "shippingDimY" : 6.2000000000000002,
        "shippingDimZ" : 35.299999999999997,
        "shippingDimensionX" : 25.600000000000001,
        "shippingDimensionY" : 6.2000000000000002,
        "shippingDimensionZ" : 35.299999999999997,
        "shippingTaxCode" : "2038346",
        "smallFormatEligible" : true,
        "stockWaterMark" : 44,
        "storePickupable" : true,
        "submapCode" : 0,
        "tagCode" : 0,
        "thresholdShippingEligible" : false,
        "tweTaxCode" : "2042533",
        "vendorItemNum" : "X322BV-HD",
        "weight" : 26.550000000000001,
        "wrapCode" : 0
    } },
    "specialPricing" : null,
    "unitCount" : "0",
    "uom" : null,
    "upc" : "0079234323252"
}
]